version: '3'
services:
  api:
    image: chaseway/rustapi
    environment:
      DATABASE_URL: "sqlite:C:/Users/Chase Wayland/Independent_Study-Backend_development/rustapi/database/Db"
      CLIENT_ID : "50375690088-d550pisn0njk98emapjq169fcre5iqp8.apps.googleusercontent.com"
      CLIENT_SECRET : "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"
      JWT_SECRET : "dee369bec579dcaaec2a1fabaf0d513c96ceae651396e1f4da9251839ea74fea"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#  db:
#    image:
#    restart: always
#    environment:
#
#    ports:
#      - ""
