DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS GoogleUsers;
DROP TABLE IF EXISTS MX;


CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    user_identifier INTEGER NOT NULL,
    user_email TEXT UNIQUE NOT NULL
);

CREATE TABLE GoogleUsers (
    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    sub TEXT UNIQUE NOT NULL,
    picture TEXT,
    email TEXT UNIQUE NOT NULL,
    name TEXT UNIQUE NOT NULL,
    token TEXT UNIQUE

--     calendar TEXT UNIQUE NOT NULL

);

CREATE TABLE MX (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    mx_index INTEGER NOT NULL,
    owner INTEGER  NOT NULL,
    date DATE UNIQUE NOT NULL,
    title TEXT UNIQUE NOT NULL,
    description TEXT UNIQUE NOT NULL
--     FOREIGN KEY(owner) REFERENCES user(id)
);
